// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form.h"
UserInterface::UserInterface(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
this->labelfont(3);
{ Fl_Button* o = new Fl_Button(75, 480, 95, 50, "Plot");
  o->shortcut(0xff0d);
  o->color((Fl_Color)25);
  o->selection_color(FL_RED);
  o->labeltype(FL_EMBOSSED_LABEL);
  o->labelfont(1);
  o->labelsize(20);
  o->labelcolor((Fl_Color)80);
} // Fl_Button* o
{ new Fl_Input(50, 55, 100, 30, "h");
} // Fl_Input* o
{ new Fl_Input(50, 100, 95, 35, "m");
} // Fl_Input* o
{ new Fl_Input(50, 150, 100, 35, "L");
} // Fl_Input* o
{ new Fl_Input(50, 205, 95, 35, "n");
} // Fl_Input* o
{ Fl_Box* o = new Fl_Box(225, 3, 1100, 553, "wave");
  Fl_Group::current()->resizable(o);
} // Fl_Box* o
{ new Fl_Input(30, 390, 65, 35, "x1");
} // Fl_Input* o
{ new Fl_Input(125, 390, 60, 35, "x2");
} // Fl_Input* o
{ new Fl_Input(110, 335, 70, 35, "no of points");
} // Fl_Input* o
{ Fl_Round_Button* o = new Fl_Round_Button(30, 440, 70, 15, "R");
  o->down_box(FL_ROUND_DOWN_BOX);
} // Fl_Round_Button* o
{ Fl_Round_Button* o = new Fl_Round_Button(105, 440, 70, 15, "Im");
  o->down_box(FL_ROUND_DOWN_BOX);
} // Fl_Round_Button* o
end();
}
